name: tofu
description: Closure template compiler for Dart.
author: Tobe O <thosakwe@gmail.com>
version: 0.0.0
homepage: https://github.com/thosakwe/dart_tofu
environment:
  sdk: ">=1.19.0"
dependencies:
  args: ^0.13.4
  build: ^0.7.0
  code_builder: ^1.0.0-beta
  recase: ^1.0.0
  soy: ^0.0.0
executables:
  dofu: dofu